root: true
env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  no-mixed-spaces-and-tabs: 0
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-explicit-any': off
  import/no-unresolved: [0, { commonjs: true, amd: true }]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  '@typescript-eslint/consistent-type-imports':
    - error
  object-curly-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - never
  semi:
    - error
    - never
